# -*- coding: utf-8 -*-
"""raspbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mfFwVJVIQEVpLXSaRwSWnZ9V6BVUjj2r
"""

import sys
import time
import serial
import requests

# 1. Add and load the library path
sys.path.append('/home/pi/project_demo/lib')
try:
    from McLumk_Wheel_Sports import *
except ImportError:
    print("Non Library. Check find road")

    def move_forward(speed): pass
    def move_backward(speed): pass
    def rotate_left(speed): pass
    def rotate_right(speed): pass
    def stop(): pass
    bot = None

#2. Server and communication settings
serverip = "10.143.218.171" #it is change when Hotspot on-and-off
SERVER_URL = f"http://{serverip}:8000/raspbot"
SERVER_CLEAR_URL = f"http://{serverip}:8000/alert"

ser = None
try:
    ser = serial.Serial('/dev/ttyACM0', 9600, timeout=1)
    print("Connect Aduino")
except:
    try:
        ser = serial.Serial('/dev/ttyUSB0', 9600, timeout=1)
        print("Connect Aduino")
    except:
        print("Cannot find Aduino")

#3. Robot state variables
student_num = {
    "Junsang Park": 1,  # A position
    "Siyeon Sohn": 2    # B position
}
last_known_status = {}
current_robot_pos = 1
speed = 40

# 4. Function definition

def line_tracking(duration=3):  # duration is time(second)
    print(f"TRACKING: {duration}초간 라인 트래킹")
    start_time = time.time()
    try:
        while time.time() - start_time < duration:
            if bot is None: break

            # Read sensor
            track_data = bot.read_data_array(0x0a, 1)
            track = int(track_data[0])

            x1 = (track >> 3) & 0x01
            x2 = (track >> 2) & 0x01
            x3 = (track >> 1) & 0x01
            x4 = track & 0x01

            lineL1, lineL2, lineR1, lineR2 = x2, x1, x3, x4

            if lineL1 == 0 and lineL2 == 0 and lineR1 == 0 and lineR2 == 0:
                move_forward(speed)
            elif (lineL2 == 0 or lineL1 == 0) and lineR2 == 0:
                rotate_right(speed)
                time.sleep(0.05)
            elif lineL1 == 0 and (lineR2 == 0 or lineR1 == 0):
                rotate_left(int(speed*1.5))
                time.sleep(0.15)
            elif lineL1 == 0:
                rotate_left(speed)
                time.sleep(0.02)
            elif lineR2 == 0:
                rotate_right(speed)
                time.sleep(0.01)
            elif lineL2 == 0 and lineR1 == 1:
                rotate_left(speed)
            elif lineL2 == 1 and lineR1 == 0:
                rotate_right(speed)
            elif lineL2 == 0 and lineR1 == 0:
                move_forward(speed)

            time.sleep(0.01)
    except Exception as e:
        print(f"Error in line-tracking: {e}")
    finally:
        stop()
        print("Line tracking finished.")

# [Senario 1] A to B
def move_A_to_B():
    print("[Move] A -> B")
    line_tracking(5)

    for x in range(3):
        move_backward(15)
        time.sleep(0.3)
        stop()

        if current_status == "talking":
            ser.write(b'1')  # focus
        elif current_status == "phone":
            codes = [b'2', b'3', b'4']
            ser.write(codes[x])
        elif current_status == "sleeping":
            ser.write(b'5')  # wake up
        elif current_status == "staring":
            codes = [b'6', b'7', b'8']
            ser.write(codes[x])
        time.sleep(0.5)

        move_forward(30)
        time.sleep(0.5)

    stop()
    time.sleep(0.1)
    move_backward(30)
    time.sleep(0.7)
    rotate_right(10)
    time.sleep(0.8)
    stop()

    line_tracking(0.3)
    stop()

# [Scenario 2] B to A
def move_B_to_A():
    print("[Move] B -> A")
    line_tracking(5)

    for x in range(3):
        move_backward(15)
        time.sleep(0.3)
        stop()
        if current_status == "talking":
            ser.write(b'1')  # focus
        elif current_status == "phone":
            codes = [b'2', b'3', b'4']
            ser.write(codes[x])
        elif current_status == "sleeping":
            ser.write(b'5')  # wake up
        elif current_status == "staring":
            codes = [b'6', b'7', b'8']
            ser.write(codes[x])
        time.sleep(0.5)

        move_forward(30)
        time.sleep(0.5)

    stop()
    time.sleep(0.1)
    move_backward(30)
    time.sleep(0.7)
    rotate_left(10)
    time.sleep(0.8)
    stop()

    line_tracking(0.3)
    stop()

# [Scenario 3] A to A / B to B
def warn_in_place():
    print("제자리 경고")
    move_backward(10)
    time.sleep(0.5)
    if target_pos == 1:
        rotate_right(30)
    else:
        rotate_left(30)
    time.sleep(0.6)

    line_tracking(3)

    for x in range(3):
        move_backward(15)
        time.sleep(0.3)
        stop()

        if current_status == "talking":
            ser.write(b'1')  # focus
        elif current_status == "phone":
            codes = [b'2', b'3', b'4']
            ser.write(codes[x])
        elif current_status == "sleeping":
            ser.write(b'5')  # wake up
        elif current_status == "staring":
            codes = [b'6', b'7', b'8']
            ser.write(codes[x])
        time.sleep(0.5)

        move_forward(30)
        time.sleep(0.5)

    stop()
    time.sleep(0.1)
    move_backward(30)
    time.sleep(0.5)
    if target_pos == 1:
        rotate_left(30)
    else:
        rotate_right(30)
    time.sleep(0.7)

    line_tracking(0.3)
    stop()


#5. Main execution loop
print(f"Raspbot Start! (Initial position: {current_robot_pos})")

try:
    while True:
        try:
            # 1. Check Server
            response = requests.get(SERVER_URL, timeout=3)
            alert_board = {}
            if response.status_code == 200:
                try:
                    alert_board = response.json()
                except:
                    pass

            if not alert_board:
                time.sleep(1)
                continue

            # 2. Alert
            for name, info in alert_board.items():
                current_status = info['status']

                if last_known_status.get(name) != current_status:
                    last_known_status[name] = current_status
                    print(f"\n[Detect] {name} -> {current_status}")

                if current_status in ['phone', 'sleeping', 'staring', 'talking']:
                    target_pos = student_num.get(name, 0)

                    if target_pos != 0:
                        print(f"[Deployment] {name} ({current_status}) @ Pos {target_pos}")

                        if current_robot_pos == 1 and target_pos == 2:
                            move_A_to_B()
                            current_robot_pos = 2
                        elif current_robot_pos == 2 and target_pos == 1:
                            move_B_to_A()
                            current_robot_pos = 1
                        else:
                            warn_in_place()

                        print(f"Current: {current_robot_pos}")

                        try:
                            requests.delete(f"{SERVER_CLEAR_URL}/{name}", timeout=0.5)
                            if name in last_known_status:
                                del last_known_status[name]
                            print(f" {name} End")
                        except Exception as e:
                            print(f"Error in Server Connection: {e}")
                    else:
                        print(f"Non Position: {name}")

        except Exception as e:
            print(f"Loop Error: {e}")

        time.sleep(1)

except KeyboardInterrupt:
    print("End Program")
    stop()
    if 'bot' in globals() and bot:
        del bot
